// onboarding/src/content/code-map.mjs
export const CODE_MAP = {
    annotations: [
        // directories
        { path: 'components', note: 'React UI — editor shell, canvas, panels, modals; feature subdirs (canvas, cloud, docs, gallery, json, moderation, properties, sidebar).' },
        { path: 'pages', note: 'Route-level components. EditorPage is the product; everything else orbits it.' },
        { path: 'services', note: 'Client logic kept DOM-light: PDF export, text layout, schema migrations, typed API wrapper, generator sandbox.' },
        { path: 'server', note: 'Express 5 API. app.js is the createApp() factory; index.js just boots it. SQLite in dev, Postgres in prod.' },
        { path: 'server/routes', note: 'Six route files — four core (me, projects, gallery, mergeRequests) plus the two moderation-era ones. Nearly every endpoint lives here; app.js keeps two of its own (/api/track, /api/stats) plus the SPA fallback. Rounds add endpoints to existing files — a new route file is rare and deliberate.' },
        { path: 'server/migrations', note: 'The migration ledger (index.js). NEVER edit an applied migration — append a new one. Three of them install database triggers: 011 and 014 make the audit tables append-only, 012 refuses sessions for suspended users.' },
        { path: 'server/middleware', note: 'checkOrigin (CSRF), rate limits, requireAdmin/requireOwner (live config membership on every request), requireUsername.' },
        { path: 'shared', note: 'Plain ESM imported by BOTH client and server — generator metadata and shared validation rules. The diff engine lives here too, but only the server imports it today.' },
        { path: 'hooks', note: 'Three React hooks: useCurrentUser (session), useGalleryDetail (shared by gallery page + modal), and useWorkspaceProjectWrites (working-copy publication and coalesced local saves).' },
        { path: 'lib', note: 'Docs content loading/validation/search + the better-auth browser client.' },
        { path: 'tests', note: 'Component vitest suites flat in tests/unit, server suites in tests/unit/server, Playwright e2e in tests/e2e, shared helpers (incl. the gallery-sample harness) in tests/helpers.' },
        { path: 'docs-content', note: 'The in-app /docs product: 25 tutorials + 83 reference entries as markdown, validated at load — a bad link fails the unit suite.' },
        { path: 'docs-capture', note: 'Committed Playwright pipeline that regenerates all 64 docs assets — 50 PNG stills plus 14 animated WebP clips — deterministically (node docs-capture/run.js <track>).' },
        { path: 'tutorial', note: 'The video-tutorial production pipeline: storyboards, Chirp narration, paced recording, ffmpeg assembly.' },
        { path: 'gallery-samples', note: '20 flagship sample products as generator scripts, validated by a committed harness (structure, links, bounds, example chrome).' },
        { path: 'docs/superpowers', note: 'Specs and plans for every round — the paper trail of the house method. Read a spec before touching its feature.' },
        { path: 'public', note: 'Static assets, including the long-form project walkthrough this playground is distilled from.' },
        { path: 'scripts', note: 'Utility scripts (lighthouse audit runner).' },
        { path: 'onboarding', note: 'This playground: authored src/ + build.mjs assembling the committed index.html you are reading.' },
        // client files
        { path: 'App.tsx', note: 'All routes, statically imported (one main chunk by design; only /docs and the listing editor are lazy). The gallery modal’s background-location split lives here.' },
        { path: 'index.tsx', note: 'Client entry — mounts App under the router.' },
        { path: 'types.ts', note: 'AppState and every document type. Start reading the codebase here.' },
        { path: 'components/ProjectEditor.tsx', note: 'Editor shell: toolbar, canvas, right-hand panels, selection model, undo checkpoints.' },
        { path: 'components/Canvas.tsx', note: 'The DOM canvas (not <canvas>): pages, marquee, drag. Hit-testing delegates to services/hitTest.ts.' },
        { path: 'components/canvas/CanvasElement.tsx', note: 'Single element renderer — including THE DOMPurify.sanitize call, the one place foreign SVG ever reaches the DOM.' },
        { path: 'components/HierarchyGeneratorModal.tsx', note: 'Generator modal: two script editors, sandboxed Preview, atomic Apply, Saved Generator badge.' },
        { path: 'components/LayersPanel.tsx', note: 'Layers: hide/lock/color/rename/drag-reorder; hidden = excluded from canvas, PDF and thumbnails via one shared filter.' },
        { path: 'components/cloud/CloudMenu.tsx', note: 'Save/history/publish menu; the signed-out / no-username / ready 3-way branch; forked-from indicator.' },
        { path: 'components/cloud/PublishModal.tsx', note: 'Publish wizard. Compares rendered previews against picked pages and refuses partial sets.' },
        { path: 'components/cloud/EditListingModal.tsx', note: 'Edit a published listing without republishing. It holds the listing identity its save is refused without (published commit + published_at); shared/publicationTag.js turns that pair into the composite If-Match token cloudApi sends.' },
        { path: 'components/gallery/ProjectCard.tsx', note: 'The shared card with rollover previews — gallery grids, strips, and profile pages all render this one component (the ?view=all directory deliberately uses a compact table instead).' },
        { path: 'pages/EditorPage.tsx', note: 'Route wrapper that anchors the pdf.js-heavy chunk (EditorPage → CloudMenu → PublishModal → thumbnailService).' },
        { path: 'pages/GalleryPage.tsx', note: 'Three modes in one page: sections view, URL-param filtered grid, ?view=all sortable directory.' },
        { path: 'pages/MergeRequestPage.tsx', note: 'MR review: structured change list, conflict warnings, before/after preview; owner state comes from the server’s isTargetOwner.' },
        // server files
        { path: 'server/app.js', note: 'createApp() factory. Middleware order is load-bearing: helmet → cors → host allow-list → auth (before express.json!) → origin check → rate limit → routes → SPA fallback.' },
        { path: 'server/index.js', note: 'Boot: run migrations, then listen. Production refuses to boot with OWNER_EMAILS empty.' },
        { path: 'server/auth.js', note: 'better-auth config. The hooks are the choke points: signup cap, password policy, admin-path denial (normalized-path bypass fix).' },
        { path: 'server/db.js', note: 'query() working identically on Postgres and SQLite. Replaced a DROP TABLE CASCADE dev bootstrap — the first thing the gallery work fixed.' },
        { path: 'server/migrations.js', note: 'Run-once migration runner: advisory-locked, transactional, with a test that injects mid-migration failure and watches rollback.' },
        { path: 'server/migrations/index.js', note: 'All 16+ migrations inline, pg + sqlite variants. 012 installs the BEFORE INSERT trigger refusing sessions for suspended users; 013 creates no trigger — it replaces that trigger’s function so it reads the wall clock (Postgres only; the sqlite variant is a no-op).' },
        { path: 'server/routes/projects.js', note: 'The big file: CRUD, commits, publish, publication PATCH, fork. The CAS save and published-commit pinning idioms live here.' },
        { path: 'server/routes/gallery.js', note: 'Public reads, reviews, tags, reports. The LIKE … ESCAPE wildcard fix is here.' },
        { path: 'server/routes/mergeRequests.js', note: 'MR lifecycle: live diff recompute per view, merge re-verified under the target-head lock.' },
        { path: 'server/middleware/guards.js', note: 'requireUsername guards exactly the six content-creating routes; requireAdmin/requireOwner check live config membership, never trusting a stored role.' },
        { path: 'server/validateAppState.js', note: 'Compatibility re-export preserving the server import path for the shared AppState validator.' },
        { path: 'server/stateCodec.js', note: 'gzip encode/decode for full-snapshot commits.' },
        { path: 'server/projectLocks.js', note: 'lockProjectRows — paired with db.js’s withTransaction, the write-path integrity layer every later round leans on.' },
        { path: 'server/email.js', note: 'Resend-or-console fail-safe email. A missing key never weakens sign-in blocking. First of the dotenv seals.' },
        { path: 'server/signupCap.js', note: 'Verified-only cap counting, fails open; SIGNUP_CAP trimmed first because Number(" ") === 0 once meant “closed”.' },
        { path: 'server/ownerAuthority.js', note: 'OWNER_EMAILS reconciliation — the only root of trust for the owner role; no HTTP path grants it.' },
        { path: 'server/platformAudit.js', note: 'Append-only audit writes; an audit-insert failure rolls back the action it was recording.' },
        // services + shared
        { path: 'services/cloudApi.ts', note: 'One typed wrapper for every server endpoint. New endpoint ⇒ new function here.' },
        { path: 'services/migration.ts', note: 'CURRENT_SCHEMA_VERSION and the v1→v11 chain. Presets and generator imports must stamp versions explicitly.' },
        { path: 'services/textLayout.ts', note: 'The renderer-independent text engine: segmentation, wrap, ellipsis, shrink — measurement injected.' },
        { path: 'services/pdfService.ts', note: 'jsPDF export: Unicode font embedding, link annotations from every branch, svg2pdf, grayscale.' },
        { path: 'services/thumbnailService.ts', note: 'jsPDF → pdfjs-dist → WebP preview pipeline (pdfjs pinned after npm latest shipped broken).' },
        { path: 'services/generatorSandbox.ts', note: 'The generator trust boundary: sandboxed iframe, disposable worker, captured intrinsics, 10 s timeout.' },
        { path: 'shared/diff.js', note: 'The three-way diff/merge engine — under 200 lines, no dependencies, server-side today (the client renders the ChangeSet the server computed). This playground bundles the real thing (Merge Lab).' },
        { path: 'shared/generatorMetadata.js', note: 'Generator provenance shape + size caps, shared by validator, diff, and client.' },
        { path: 'shared/validateAppState.js', note: 'Browser-safe implementation of the structural AppState gate: shape, 5 MB cap, node/element caps.' },
        // meta
        { path: 'deploy.sh', note: 'Fail-closed deploy script — with its own unit tests, after review found it plowing on past failed builds.' },
        { path: 'SCHEMA_CHANGELOG.md', note: 'Schema history through v10 (v11 shipped without its entry — a documented, honest residual).' },
        { path: 'playwright.config.cjs', note: 'e2e config; carries one of the dotenv seals (present-but-empty RESEND_API_KEY).' },
        { path: 'vite.config.ts', note: 'Vite + vitest config: jsdom env, worktree/scratch excludes explained in comments.' },
        { path: 'tests/helpers/gallerySampleHarness.ts', note: 'Executes both generator scripts of every sample product exactly the way the modal does, then validates structure, links, bounds.' },
    ],
    anchors: [
        { id: 'diff-changeset', file: 'shared/diff.js', start: 'export const computeChangeSet', end: 'const touchedTemplates' },
        { id: 'diff-threeway', file: 'shared/diff.js', start: 'export const threeWayDiff', lines: 30 },
        { id: 'diff-apply', file: 'shared/diff.js', start: 'export const applyChangeSet', lines: 28 },
        { id: 'textlayout-engine', file: 'services/textLayout.ts', start: 'export function createTextLayoutEngine(', lines: 30 },
        { id: 'sandbox-parse', file: 'services/generatorSandbox.ts', start: 'const parseMessage = (message: unknown, requestToken: string)', lines: 21 },
        { id: 'migration-trigger', file: 'server/migrations/index.js', start: "id: '012_session_suspension_guard',", lines: 30 },
        { id: 'publish-route', file: 'server/routes/projects.js', start: "router.post('/api/projects/:id/publish'", lines: 26 },
        { id: 'validate-appstate', file: 'shared/validateAppState.js', start: 'export const validateAppState = (state)', lines: 24 },
        { id: 'email-seal', file: 'server/email.js', start: '// Fail-safe: no RESEND_API_KEY', lines: 14 },
        { id: 'auth-hooks', file: 'server/auth.js', start: 'databaseHooks: {', lines: 30 },
        { id: 'spa-fallback', file: 'server/app.js', start: '// Must pass a relative filename', lines: 8 },
    ],
    deepDives: [
        { id: 'diff-engine', title: 'shared/diff.js — the whole merge system in under 200 lines',
          tagline: 'Diffs whole templates, so schema rounds ride along for free.',
          sections: [
            { text: 'computeChangeSet answers “what changed between two states” at the granularity of variants and templates — never text lines. stableStringify (sorted keys) is the entire equality story: two objects are equal iff their canonical strings match. Note nodesChanged is a single boolean: the node hierarchy is compared wholesale.', anchorId: 'diff-changeset' },
            { text: 'threeWayDiff computes both sides’ change sets against the common ancestor, then looks for genuine overlap. It detects exactly six conflict classes: the same template changed differently, a variant removed on one side and modified on the other, a variant added on both sides with different content, a variant renamed differently on both sides, the node hierarchy rewritten differently, and the generator — one atomic value, never line-merged. Changes that do not overlap coexist.', anchorId: 'diff-threeway' },
            { text: 'applyChangeSet replays the fork’s changes on top of the CURRENT upstream state (not the ancestor) — preserving whatever upstream changed independently. The server re-runs conflict detection immediately before writing; the client only ever renders.', anchorId: 'diff-apply' },
            { text: 'Because it diffs whole templates, the layers round (v8), overflow (v10) and padding (v11) all needed ZERO diff changes. Generator provenance (v9) is the one exception, and it proves the rule: the generator is not inside a template, so it had to earn its own equality rule, its own change kind and its own conflict case — about thirty lines. A schema mismatch between fork and upstream deliberately blocks the diff instead.' },
          ] },
        { id: 'text-layout', title: 'services/textLayout.ts — one engine, two renderers',
          tagline: 'Canvas and PDF cannot drift: they consume the same decisions.',
          sections: [
            { text: 'The engine owns segmentation, greedy wrap, ellipsis, shrink-to-fit and block sizing, with measurement injected as a function — so a canvas context and jsPDF metrics produce byte-identical layout decisions, and tests can inject fake metrics.', anchorId: 'textlayout-engine' },
            { text: 'War stories encoded in its fix commits: the ellipsis search binary-searched grapheme counts, assuming width is monotonic in count (it isn’t guaranteed) — now a linear scan honoring the minimum-removal contract. Greedy wrap re-measured whole candidate lines per grapheme (O(n²)) — now single-pass with tests bounding measure-call counts.' },
            { text: 'Grapheme safety comes from Intl.Segmenter with a bundled fallback (services/graphemes.ts); padding arrives pre-resolved (resolveTextContentBox shrinks the box before the engine sees it), so the engine never learns padding exists.' },
          ] },
        { id: 'generator-sandbox', title: 'The generator sandbox — running strangers’ code',
          tagline: 'Opening a project never executes anything. Previewing executes it in a cage.',
          sections: [
            { text: 'Since schema v9 a project can carry its generator source. That changed the trust model: the old Run button evaluated scripts with new Function in the app realm; Preview → Apply replaced it. Preview spawns a sandboxed iframe (no allow-same-origin, connect-src none) which spawns a disposable Worker, talks over a closure-private MessagePort, and dies on a 10-second timeout.' },
            { text: 'parseMessage is the trust boundary on the way back: every message must carry the request token, and native intrinsics were captured before evaluated source ran — so a script can’t forge results or hide oversized output behind a patched byte-length getter.', anchorId: 'sandbox-parse' },
            { text: 'The hardening commits read like an attack log: Worker/BroadcastChannel/postMessage fan-out denied inside the sandbox, a supervisor Worker so an infinite loop can’t outlive cancellation, reference-graph traversal bounded so malformed persisted input can’t hang rendering. Apply is one atomic state replace + one undo checkpoint.' },
          ] },
        { id: 'migrations', title: 'Migrations — guarantees the database itself enforces',
          tagline: 'Some invariants are too important to be code conventions.',
          sections: [
            { text: 'The runner applies each migration once, in order, under an advisory lock and a transaction — two servers booting at once can’t double-apply DDL, and a regression test injects a mid-migration failure and watches the half-applied statement roll back.' },
            { text: '012 is the interesting one: a BEFORE INSERT trigger on the session table refuses new sessions for actively-suspended users — closing a race no amount of session-deleting could. 013 fixed the fix: Postgres CURRENT_TIMESTAMP is frozen at transaction start, so an insert that waited on the suspension’s row lock evaluated stale pre-wait time; the trigger now reads the wall clock.', anchorId: 'migration-trigger' },
            { text: 'The moderation audit table (011, 014) rejects UPDATE and DELETE by trigger — immutability as a database property — and records actor/target as values, not foreign keys, so deleting an account can’t erase its history.' },
          ] },
        { id: 'publication-pinning', title: 'Publication pinning — public means what you published',
          tagline: 'The gallery never tracks your private head.',
          sections: [
            { text: 'Publish validates, locks and writes in one transaction, and sets published_commit_id — the only commit public readers ever resolve. Ordinary saves and merges advance only the private head. This model came out of a whole-branch review that caught gallery readers being served the live head — promoted to “disclosure hazard” the day generator source became public.', anchorId: 'publish-route' },
            { text: 'Listing metadata is pinned at publish too (name, description, tags — migration 010), so a private rename can’t silently rename a gallery card. The later PATCH /publication endpoint edits the listing without touching published_commit_id or published_at — the second omission is load-bearing: “Recently updated” sorts by published_at, and a tag fix must not be free promotion.' },
            { text: 'The PATCH carries a composite If-Match token — published_commit_id AND percent-encoded published_at — because republishing an unchanged commit is legal, so a version-only token would wave through exactly the stale-dialog overwrite the token exists to stop.' },
          ] },
        { id: 'validate-appstate', title: 'validateAppState — the one gate every stored AppState passes',
          tagline: 'Create, commit, merge: three server call sites, one shared structural validator.',
          sections: [
            { text: 'The browser-safe implementation lives in shared/validateAppState.js; server/validateAppState.js is a compatibility re-export. Shape checks, a 5 MB cap, and node/element count caps are enforced before anything is stored. The server has exactly three call sites, one per path that accepts an AppState from a client: project create, commits, and the merge endpoint’s produced result (a merge that validates badly refuses rather than writing). Publish is deliberately NOT one of them: it takes listing fields and an If-Match head, never a state, and pins a commit that was already validated on the way in.', anchorId: 'validate-appstate' },
            { text: 'It deliberately validates structure, not semantics: unknown extra fields ride along (that tolerance is what let layers/overflow/padding ship without server lockstep), while the client-side schema migration owns upgrading old documents.' },
          ] },
        { id: 'dotenv-seals', title: 'The dotenv seals — deleting a variable is an invitation',
          tagline: 'Sealed four times before it stayed sealed.',
          sections: [
            { text: 'The server loads dotenv at import time, and dotenv re-populates any MISSING variable from .env. So `delete process.env.RESEND_API_KEY` before tests doesn’t protect anything — the next import puts it back. Every guard is present-but-empty (`= \'\'`), which dotenv never overrides, with a regression test asserting the seal holds AFTER dotenv has loaded.', anchorId: 'email-seal' },
            { text: 'The same trap was found and sealed in four places as real credentials arrived: the Playwright webServer config, the tutorial recording servers, the deploy script’s own .env loader (which also word-split quoted values and broke a production deploy), and the unit-test helpers — discovered when a routine full-suite run sent forty real verification emails to @test.dev addresses.' },
          ] },
        { id: 'auth-stack', title: 'The auth stack — hooks as choke points',
          tagline: 'Everything app-specific hangs off better-auth hooks, not forked library code.',
          sections: [
            { text: 'databaseHooks.user.create.before is the signup-cap choke point: both email signup and first-time Google OAuth pass through user creation, and returning OAuth users never do — the one place path-based middleware can’t be blind-sided. Its error message surfaces in the OAuth error callback (spaces underscored), which the login page decodes into the waitlist panel.', anchorId: 'auth-hooks' },
            { text: 'hooks.before denies /admin/* INSIDE better-auth, where the path is already normalized — Express-level blocking was bypassed by percent-encoded dot-segments that normalized back to /admin/* inside the library. Red tests proved unban and role promotion answered 200 to a non-admin before the deny moved.' },
            { text: 'Above admin sits a deployment-controlled owner: OWNER_EMAILS is the only root of trust, reconciled at startup and signup in one transaction; requireAdmin/requireOwner demand CURRENT config membership on every request — a stored role outliving its config entry grants nothing.' },
          ] },
    ],
};
