// onboarding/src/content/code-map.mjs
export const CODE_MAP = {
    annotations: [
        // directories
        { path: 'components', note: 'React UI — editor shell, canvas, panels, modals; feature subdirs (cloud, gallery, canvas, properties, sidebar, docs, moderation).' },
        { path: 'pages', note: 'Route-level components. EditorPage is the product; everything else orbits it.' },
        { path: 'services', note: 'Client logic kept DOM-light: PDF export, text layout, schema migrations, typed API wrapper, generator sandbox.' },
        { path: 'server', note: 'Express 5 API. app.js is the createApp() factory; index.js just boots it. SQLite in dev, Postgres in prod.' },
        { path: 'server/routes', note: 'All endpoints in five files (+2 moderation-era files). Rounds add endpoints to existing files — a new route file is rare and deliberate.' },
        { path: 'server/migrations', note: 'The migration ledger (index.js). NEVER edit an applied migration — append a new one. Two migrations are database triggers.' },
        { path: 'server/middleware', note: 'checkOrigin (CSRF), rate limits, requireAdmin/requireOwner (live config membership on every request), requireUsername.' },
        { path: 'shared', note: 'Plain ESM imported by BOTH client and server — the three-way diff engine and generator provenance rules.' },
        { path: 'hooks', note: 'Two React hooks: useCurrentUser (session) and useGalleryDetail (shared by gallery page + modal).' },
        { path: 'lib', note: 'Docs content loading/validation/search + the better-auth browser client.' },
        { path: 'tests', note: 'Component vitest suites flat in tests/unit, server suites in tests/unit/server, Playwright e2e in tests/e2e, shared helpers (incl. the gallery-sample harness) in tests/helpers.' },
        { path: 'docs-content', note: 'The in-app /docs product: 25 tutorials + 83 reference entries as markdown, validated at load — a bad link fails the unit suite.' },
        { path: 'docs-capture', note: 'Committed Playwright pipeline that regenerates all 64 docs screenshots deterministically (node docs-capture/run.js <track>).' },
        { path: 'tutorial', note: 'The video-tutorial production pipeline: storyboards, Chirp narration, paced recording, ffmpeg assembly.' },
        { path: 'gallery-samples', note: '20 flagship sample products as generator scripts, validated by a committed harness (structure, links, bounds, example chrome).' },
        { path: 'docs/superpowers', note: 'Specs and plans for every round — the paper trail of the house method. Read a spec before touching its feature.' },
        { path: 'public', note: 'Static assets, including the long-form project walkthrough this playground is distilled from.' },
        { path: 'scripts', note: 'Utility scripts (lighthouse audit runner).' },
        { path: 'onboarding', note: 'This playground: authored src/ + build.mjs assembling the committed index.html you are reading.' },
        // client files
        { path: 'App.tsx', note: 'All routes, statically imported (one main chunk by design; only /docs and the listing editor are lazy). The gallery modal’s background-location split lives here.' },
        { path: 'index.tsx', note: 'Client entry — mounts App under the router.' },
        { path: 'types.ts', note: 'AppState and every document type. Start reading the codebase here.' },
        { path: 'components/ProjectEditor.tsx', note: 'Editor shell: toolbar, canvas, right-hand panels, selection model, undo checkpoints.' },
        { path: 'components/Canvas.tsx', note: 'The DOM canvas (not <canvas>): pages, marquee, drag. Hit-testing delegates to services/hitTest.ts.' },
        { path: 'components/canvas/CanvasElement.tsx', note: 'Single element renderer — including THE DOMPurify.sanitize call, the one place foreign SVG ever reaches the DOM.' },
        { path: 'components/HierarchyGeneratorModal.tsx', note: 'Generator modal: two script editors, sandboxed Preview, atomic Apply, Saved Generator badge.' },
        { path: 'components/LayersPanel.tsx', note: 'Layers: hide/lock/color/rename/drag-reorder; hidden = excluded from canvas, PDF and thumbnails via one shared filter.' },
        { path: 'components/cloud/CloudMenu.tsx', note: 'Save/history/publish menu; the signed-out / no-username / ready 3-way branch; forked-from indicator.' },
        { path: 'components/cloud/PublishModal.tsx', note: 'Publish wizard. Compares rendered previews against picked pages and refuses partial sets.' },
        { path: 'components/cloud/EditListingModal.tsx', note: 'Edit a published listing without republishing; carries the composite If-Match token.' },
        { path: 'components/gallery/ProjectCard.tsx', note: 'The shared card with rollover previews — gallery, profile, and directory all render this one component.' },
        { path: 'pages/EditorPage.tsx', note: 'Route wrapper that anchors the pdf.js-heavy chunk (EditorPage → CloudMenu → PublishModal → thumbnailService).' },
        { path: 'pages/GalleryPage.tsx', note: 'Three modes in one page: sections view, URL-param filtered grid, ?view=all sortable directory.' },
        { path: 'pages/MergeRequestPage.tsx', note: 'MR review: structured change list, conflict warnings, before/after preview; owner state comes from the server’s isTargetOwner.' },
        // server files
        { path: 'server/app.js', note: 'createApp() factory. Middleware order is load-bearing: helmet → cors → host allow-list → auth (before express.json!) → origin check → rate limit → routes → SPA fallback.' },
        { path: 'server/index.js', note: 'Boot: run migrations, then listen. Production refuses to boot with OWNER_EMAILS empty.' },
        { path: 'server/auth.js', note: 'better-auth config. The hooks are the choke points: signup cap, password policy, admin-path denial (normalized-path bypass fix).' },
        { path: 'server/db.js', note: 'query() working identically on Postgres and SQLite. Replaced a DROP TABLE CASCADE dev bootstrap — the first thing the gallery work fixed.' },
        { path: 'server/migrations.js', note: 'Run-once migration runner: advisory-locked, transactional, with a test that injects mid-migration failure and watches rollback.' },
        { path: 'server/migrations/index.js', note: 'All 16+ migrations inline, pg + sqlite variants. 012/013 are BEFORE INSERT triggers refusing sessions for suspended users.' },
        { path: 'server/routes/projects.js', note: 'The big file: CRUD, commits, publish, publication PATCH, fork. The CAS save and published-commit pinning idioms live here.' },
        { path: 'server/routes/gallery.js', note: 'Public reads, reviews, tags, reports. The LIKE … ESCAPE wildcard fix is here.' },
        { path: 'server/routes/mergeRequests.js', note: 'MR lifecycle: live diff recompute per view, merge re-verified under the target-head lock.' },
        { path: 'server/middleware/guards.js', note: 'requireUsername guards exactly the six content-creating routes; requireAdmin/requireOwner check live config membership, never trusting a stored role.' },
        { path: 'server/validateAppState.js', note: 'Structural gate for every stored AppState: shape, 5 MB cap, node/element caps.' },
        { path: 'server/stateCodec.js', note: 'gzip encode/decode for full-snapshot commits.' },
        { path: 'server/projectLocks.js', note: 'withTransaction + lockProjectRows — the write-path integrity layer every later round leans on.' },
        { path: 'server/email.js', note: 'Resend-or-console fail-safe email. A missing key never weakens sign-in blocking. First of the dotenv seals.' },
        { path: 'server/signupCap.js', note: 'Verified-only cap counting, fails open; SIGNUP_CAP trimmed first because Number(" ") === 0 once meant “closed”.' },
        { path: 'server/ownerAuthority.js', note: 'OWNER_EMAILS reconciliation — the only root of trust for the owner role; no HTTP path grants it.' },
        { path: 'server/platformAudit.js', note: 'Append-only audit writes; an audit-insert failure rolls back the action it was recording.' },
        // services + shared
        { path: 'services/cloudApi.ts', note: 'One typed wrapper for every server endpoint. New endpoint ⇒ new function here.' },
        { path: 'services/migration.ts', note: 'CURRENT_SCHEMA_VERSION and the v1→v11 chain. Presets and generator imports must stamp versions explicitly.' },
        { path: 'services/textLayout.ts', note: 'The renderer-independent text engine: segmentation, wrap, ellipsis, shrink — measurement injected.' },
        { path: 'services/pdfService.ts', note: 'jsPDF export: Unicode font embedding, link annotations from every branch, svg2pdf, grayscale.' },
        { path: 'services/thumbnailService.ts', note: 'jsPDF → pdfjs-dist → WebP preview pipeline (pdfjs pinned after npm latest shipped broken).' },
        { path: 'services/generatorSandbox.ts', note: 'The generator trust boundary: sandboxed iframe, disposable worker, captured intrinsics, 10 s timeout.' },
        { path: 'shared/diff.js', note: 'The three-way diff/merge engine — 189 lines, no dependencies, imported by client and server. This playground bundles the real thing (Merge Lab).' },
        { path: 'shared/generatorMetadata.js', note: 'Generator provenance shape + size caps, shared by validator, diff, and client.' },
        // meta
        { path: 'deploy.sh', note: 'Fail-closed deploy script — with its own unit tests, after review found it plowing on past failed builds.' },
        { path: 'SCHEMA_CHANGELOG.md', note: 'Schema history through v10 (v11 shipped without its entry — a documented, honest residual).' },
        { path: 'playwright.config.cjs', note: 'e2e config; carries one of the dotenv seals (present-but-empty RESEND_API_KEY).' },
        { path: 'vite.config.ts', note: 'Vite + vitest config: jsdom env, worktree/scratch excludes explained in comments.' },
        { path: 'tests/helpers/gallerySampleHarness.ts', note: 'Executes both generator scripts of every sample product exactly the way the modal does, then validates structure, links, bounds.' },
    ],
    deepDives: [],
    anchors: [],
};
