export const PLAYGROUND = {
    quizLevels: [
        { title: 'L1 · orientation', questions: [
            { q: 'What is PDF Architect, in one sentence?',
              options: ['A cloud CMS for PDF forms', 'A local-first editor for structured PDF products (planners, journals) targeting e-ink pages', 'A PDF viewer with annotations', 'A print shop backend'],
              answer: 1, why: 'Local-first is the founding constraint — everything (editing, export) works with no account; cloud/gallery is opt-in on top. See the INTRO window.' },
            { q: 'Where does an anonymous user’s project live?',
              options: ['IndexedDB', 'A cloud draft keyed by cookie', 'localStorage', 'The URL fragment'],
              answer: 2, why: 'Projects persist to browser localStorage; cloud storage only exists after an explicit “save to cloud”.' },
            { q: 'npm run dev starts…',
              options: ['Vite only', 'A Docker compose stack', 'Express serving a prebuilt dist/', 'Vite and the Express API concurrently'],
              answer: 3, why: 'package.json: concurrently "vite" "node server/index.js" — client :3000, API :3001.' },
            { q: 'Databases in dev and prod are…',
              options: ['SQLite dev, Postgres prod — one query() over both', 'Postgres everywhere', 'SQLite everywhere', 'MongoDB'],
              answer: 0, why: 'server/db.js exposes one query() over both engines and migrations carry pg and sqlite variants; the ~20 places the engines genuinely differ (FOR UPDATE, advisory locks) branch on dbType explicitly.' },
            { q: 'A “variant” is…',
              options: ['A git branch of the project', 'An alternate template set over the same node hierarchy', 'A color theme', 'A fork on the gallery'],
              answer: 1, why: 'One document, many looks: variants swap the templates; the hierarchy stays shared. types.ts is the reference.' },
            { q: 'The in-app /docs content comes from…',
              options: ['A CMS', 'Hand-written JSX pages', 'Bundled markdown in docs-content/, validated at load', 'The GitHub wiki'],
              answer: 2, why: 'docs-content/ markdown is parsed and validated in the unit suite — a broken link or duplicate slug fails the build.' },
            { q: 'How does a project become publicly visible?',
              options: ['Auto-sync once signed in', 'Sharing a link', 'Admin approval', 'An explicit publish that pins a specific commit'],
              answer: 3, why: 'Publishing pins published_commit_id; private saves never move public content. The “pinned snapshot” tour walks it.' },
            { q: 'What lives in shared/?',
              options: ['Plain ESM imported by BOTH client and server — the diff engine and generator metadata', 'CSS shared by pages', 'React context providers', 'Test fixtures'],
              answer: 0, why: 'shared/generatorMetadata.js is imported by services/generatorSandbox.ts on the client AND server/validateAppState.js on the server — same file, both sides. shared/diff.js is server-side today; the client renders the ChangeSet the server computed.' },
        ] },
        { title: 'L2 · the client', questions: [
            { q: 'The editor canvas is technically…',
              options: ['A <canvas> 2D context', 'SVG', 'Absolutely-positioned DOM elements', 'WebGL'],
              answer: 2, why: 'DOM canvas — which is why thumbnails need the jsPDF→pdfjs pipeline and why editor chrome needed isolation:isolate.' },
            { q: 'Current document schema version, defined where?',
              options: ['v7 in types.ts', 'v11 in services/migration.ts', 'v11 in server/validateAppState.js', 'v9 in shared/diff.js'],
              answer: 1, why: 'CURRENT_SCHEMA_VERSION = 11 in services/migration.ts; the server validator deliberately doesn’t own versioning.' },
            { q: 'How are layers stored (“Shape B”)?',
              options: ['Elements nested inside layer objects', 'A separate layers table in the cloud', 'CSS z-index only', 'A flat element array + layerId tags + layers metadata on the template'],
              answer: 3, why: 'Flat elements stay individually addressable, render/export only re-sort, and the diff engine needed zero changes.' },
            { q: 'Why do elements render inside an isolation:isolate wrapper?',
              options: ['So user-set z-index can never paint over selection chrome at z-100', 'Performance', 'Accessibility', 'Print fidelity'],
              answer: 0, why: 'A template with an element at z>100 covered the selection border — isolation gives elements their own stacking context.' },
            { q: 'The gallery-project-as-modal trick uses…',
              options: ['A portal + display:none page', 'React Router background locations — URL changes, page underneath keeps rendering', 'An iframe', 'Query params only'],
              answer: 1, why: 'Direct loads/refreshes render the standalone page; in-app clicks pass the current location as state. Spiked before planning.' },
            { q: 'Components call the server through…',
              options: ['fetch() inline', 'A GraphQL client', 'services/cloudApi.ts, one typed wrapper per cloud endpoint', 'React Query hooks per component'],
              answer: 2, why: 'One file to grep when an endpoint changes — ~40 typed wrappers. Two raw-fetch holdouts remain: services/analytics.ts and the public profile load in pages/ProfilePage.tsx.' },
            { q: 'Opening someone’s project that carries generator scripts…',
              options: ['Runs them to rebuild the document', 'Strips them', 'Asks for permission then runs in-page', 'Never executes them — only an explicit Preview runs, sandboxed'],
              answer: 3, why: 'Opening must never execute foreign code. Preview runs in a sandboxed iframe + disposable worker with a 10 s timeout (SANDBOX_TIMEOUT_MS, services/generatorSandbox.ts).' },
            { q: 'Which client code is code-split off the main chunk?',
              options: ['The /docs section and the Edit Listing modal', 'Every route', 'The gallery', 'Nothing'],
              answer: 0, why: 'App.tsx imports every page statically by design — there are no per-route chunks. DocsSection and the ~6 kB EditListingModal are the client’s only two lazy boundaries.' },
        ] },
        { title: 'L3 · server & data', questions: [
            { q: 'Migration policy is…',
              options: ['Edit the schema file and restart', 'Versioned, run-once, append-only — never edit an applied migration', 'ORM auto-migration', 'Manual SQL in prod'],
              answer: 1, why: 'server/migrations/index.js is a ledger; the runner is transactional and takes a Postgres advisory lock so two boots cannot race. It replaced a bootstrap that DROP TABLEd the auth tables on every start.' },
            { q: 'A cloud commit stores…',
              options: ['A gzip’d full snapshot of AppState', 'A diff against the parent', 'Only changed templates', 'A patch file'],
              answer: 0, why: 'Full snapshots (decided pre-code) make history, restore, fork and merge simple reads. stateCodec.js does the gzip.' },
            { q: 'What does publishing pin, exactly?',
              options: ['The head commit forever', 'A tag name', 'published_commit_id + listing metadata (name/description/tags) at publish time', 'A rendered PDF'],
              answer: 2, why: 'Migrations 009/010: public readers resolve only the pinned commit and pinned metadata; saves move the private head only.' },
            { q: 'A merge request’s diff is…',
              options: ['Snapshotted when opened', 'Cached for an hour', 'Recomputed live on every view', 'Computed client-side only'],
              answer: 2, why: 'A request that becomes conflicted after upstream changes is caught on view — and the merge endpoint re-verifies under lock anyway.' },
            { q: 'requireUsername guards…',
              options: ['Every /api route', 'The six content-creating routes (create/commits/publish/fork/MR/reviews) — not unpublish/delete/close', 'Only publish', 'Only the gallery'],
              answer: 1, why: 'Every write that attaches a public handle is gated; cleanup routes aren’t, so legacy no-username accounts can still reduce their own exposure.' },
            { q: 'Star-rating averages are…',
              options: ['Denormalized onto projects and updated on write', 'Computed client-side', 'Cached in Redis', 'Computed at read time with SQL AVG()'],
              answer: 3, why: 'A live AVG can’t drift the way a hand-maintained counter can — ratings change on every edit and delete.' },
            { q: 'Forking a public project gives you…',
              options: ['A private project copied from the PUBLISHED commit, with lineage recorded', 'A public linked copy', 'A branch on the original', 'Read access'],
              answer: 0, why: 'A fork starts private and copies the source’s PUBLISHED commit — not the owner’s private head, even when you fork your own project. Lineage lands in forked_from_project_id/_commit_id, which the gallery renders as attribution.' },
            { q: 'A save with a stale If-Match tag gets…',
              options: ['A silent overwrite', 'A merge attempt', 'A retry loop server-side', 'A stable 409 and no orphan commit'],
              answer: 3, why: 'Heads advance by transactional compare-and-swap; the losing writer is told cleanly and nothing half-lands.' },
        ] },
        { title: 'L4 · security & integrity', questions: [
            { q: 'The stored-XSS fix for SVG artwork was…',
              options: ['A CSP header', 'Escaping on upload', 'DOMPurify at the single place SVG is ever rendered', 'Blocking SVG in the gallery'],
              answer: 2, why: 'components/canvas/CanvasElement.tsx sanitizes with the svg/svgFilters profile — verified with a live exploit before and after.' },
            { q: 'The signup cap is enforced in…',
              options: ['Express middleware on /sign-up', 'better-auth databaseHooks.user.create.before', 'The client form', 'nginx'],
              answer: 1, why: 'The one choke point email signup AND first-time OAuth share; returning OAuth users never create a row so never hit it.' },
            { q: 'Why did the Express-level /api/auth/admin block get bypassed?',
              options: ['A missing await', 'CORS misconfig', 'A regex typo', 'Percent-encoded dot-segments normalized back to /admin/* inside better-auth'],
              answer: 3, why: 'The real deny now lives in better-auth’s hooks.before, which sees the normalized path; the Express 404 stays as defense in depth. Red tests proved the bypass first.' },
            { q: 'A suspended user trying to establish a NEW session is stopped by…',
              options: ['Session-delete sweeps', 'A BEFORE INSERT trigger on the session table', 'The client', 'Rate limiting'],
              answer: 1, why: 'Migration 012 makes it a database property — closing the race that session deletion alone can’t.' },
            { q: 'The moderation audit log is immutable because…',
              options: ['UPDATE/DELETE-rejecting triggers on the table itself', 'Code convention', 'It’s append-only S3', 'Row-level security'],
              answer: 0, why: 'Triggers on both engines; actor/target stored as values (not FKs) so deleting an account can’t erase history.' },
            { q: 'The owner role is granted by…',
              options: ['An admin promoting you', 'A signup flag', 'The first account ever created', 'OWNER_EMAILS config reconciliation at startup/signup — no HTTP path exists'],
              answer: 3, why: 'Stale stored owners drop to plain user; requireOwner checks live config membership on every request.' },
            { q: 'Uploaded preview thumbnails are validated by…',
              options: ['File extension', 'Claimed MIME type', 'Actual magic bytes + a 300 KB cap', 'Virus scan'],
              answer: 2, why: 'parseThumbnail reads the bytes; a renamed .html can’t masquerade as a .webp.' },
            { q: 'When do someone else’s generator scripts execute in your browser?',
              options: ['Only when YOU click Preview — inside the sandbox', 'On project open', 'On gallery hover', 'On fork'],
              answer: 0, why: 'Open never executes; Apply applies the previewed result; the sandbox denies network, same-origin, and worker fan-out.' },
        ] },
        { title: 'L5 · war stories', questions: [
            { q: 'Why didn’t `delete process.env.RESEND_API_KEY` protect tests from sending real email?',
              options: ['Tests ran in a subprocess', 'dotenv re-populates any MISSING variable from .env on import', 'The key was cached', 'Resend ignores env'],
              answer: 1, why: 'Deleting a variable is an invitation. Every guard is present-but-empty, asserted AFTER dotenv loads. Sealed four times.' },
            { q: 'Pre-fix, DISABLE_AUTH_RATE_LIMIT=false did what?',
              options: ['Nothing', 'Enabled stricter limits', 'Disabled brute-force protection — any value was truthy', 'Crashed boot'],
              answer: 2, why: 'enabled: !process.env.X treats "false" as disable. The fix is a strict !== "true" check.' },
            { q: 'The tag filter’s “exact match” leaked because…',
              options: ['Unescaped % and _ in the LIKE pattern matched across JSON boundaries', 'Case sensitivity', 'Unicode', 'A join bug'],
              answer: 0, why: 'Fixed with an ESCAPE clause behaving identically on Postgres and SQLite, plus a regression test.' },
            { q: 'The Change Password section had never rendered for anyone because…',
              options: ['A CSS bug', 'A feature flag', 'It required owner role', 'The code checked a.provider but better-auth returns providerId — and the unit-test mock encoded the same wrong guess'],
              answer: 3, why: 'The mandatory real-browser task caught what mocked units structurally couldn’t. pages/AccountSettingsPage.tsx.' },
            { q: 'Why does insertCommit stamp created_at itself instead of taking the database default?',
              options: ['UUIDv4 sort', 'A race in Express', 'SQLite CURRENT_TIMESTAMP has whole-second resolution and ORDER BY then falls through to a random UUID id', 'Clock skew'],
              answer: 2, why: 'Two commits in the same second would tie on created_at and order randomly. Caught inside the task that added the API, so it never shipped broken — server/routes/projects.js.' },
            { q: 'SIGNUP_CAP=" " (a stray space) originally meant…',
              options: ['Unset', 'Signups CLOSED — Number(" ") === 0', 'Default 500', 'Crash'],
              answer: 1, why: 'Trimmed first now; whitespace means unset. Same review also caught deploy --set-env-vars replacing the whole env set.' },
            { q: 'The page-dimension unit dropdown (pt/px/in/mm) spent six months, up to the layers follow-up, being…',
              options: ['Rounding wrong', 'Metric-only', 'Breaking undo', 'Purely decorative — the conversion table was imported but never called'],
              answer: 3, why: 'A multi-select refactor dropped the conversion calls, so inputs showed raw points whatever the dropdown claimed. Switching units now re-expresses size, with round-trip drift tests.' },
            { q: 'Profile pages shipped a release with zero thumbnails because…',
              options: ['Endpoint omitted the new field + card dropped its fallback + a defensive default hid the crash — and no task owned the visual outcome', 'A CDN outage', 'An auth bug', 'Image caps'],
              answer: 0, why: 'Task 1 flagged it, Task 4 guarded it, nobody owned it. The fix added the field at the source plus a profile-page test.' },
        ] },
    ],
    bugHunt: [],
    mergeScenarios: [],
    wdil: [],
};
