// onboarding/src/content/tours.mjs
// Six guided data-flow stories. Diagram tokens: {{id:label}} — steps light them
// up via their `highlight` lists. `files` are repo paths (existence is tested).
export const TOURS = [
    {
        id: 'local-first',
        title: 'Local-first: a project’s life in the browser',
        blurb: 'No account and no server required: IndexedDB remains local document authority; cloud storage is explicit opt-in through Save to cloud.',
        diagram: [
            '{{gate:WorkspaceBootstrapGate}} ──ready──▶ {{ui:EditorPage}} ──edits──▶ {{state:AppState (schema v11)}}',
            '          │ bootstrap                         │                        ├──▶ {{canvas:DOM canvas}} ──▶ {{pdf:jsPDF export}}',
            '          ▼                                   ▼                        └──▶ {{gen:generator scripts}}',
            '{{store:LocalWorkspaceStore}} ◀──commit── {{writes:useWorkspaceProjectWrites}}',
            '          │ six-store atomic writes',
            '          ▼',
            '{{idb:IndexedDB authority}} ◀──verified── {{mig:migration}} ◀──read-only── {{legacy:legacy localStorage}}',
        ],
        steps: [
            { text: 'Everything the editor knows is one JSON document: AppState. Nodes form the page hierarchy, variants hold template sets, templates hold elements, layers tag elements without restructuring them, and an optional generator block carries the scripts that produced the document.',
              files: ['types.ts'], highlight: ['state'] },
            { text: 'WorkspaceBootstrapGate owns /app startup. It calls LocalWorkspaceStore.bootstrap and does not mount EditorPage until an independently verified ready snapshot exists; opening, migration, unavailable storage, and recovery stay outside the editor.',
              files: ['App.tsx', 'components/workspace/WorkspaceBootstrapGate.tsx', 'services/localWorkspace/contracts.ts'], highlight: ['gate', 'store', 'ui'] },
            { text: 'The three-method LocalWorkspaceStore boundary — bootstrap, commit, and exportRecoveryBundle — hides transactions and recovery state. Initial migration writes all six IndexedDB stores atomically: projects, workspace, presets, pendingImports, migrationLedger, and legacyBackup. Independent read-back and a verified ledger switch authority.',
              files: ['services/localWorkspace/LocalWorkspaceStore.ts', 'services/localWorkspace/contracts.ts', 'services/localWorkspace/indexedDbAdapter.ts', 'services/localWorkspace/schema.ts'], highlight: ['store', 'idb', 'mig'] },
            { text: 'ProjectEditor reports edits to EditorPage, which sends them through useWorkspaceProjectWrites. The hook keeps the newest working copy visible while LocalWorkspaceStore coalesces saves in a per-project queue. IndexedDB checks private incarnation plus storageRevision with compare-and-swap (CAS), and a complete read-back installs each success; failed work remains available to retry or download.',
              files: ['components/ProjectEditor.tsx', 'pages/EditorPage.tsx', 'hooks/useWorkspaceProjectWrites.ts', 'services/localWorkspace/mutationQueue.ts', 'services/localWorkspace/indexedDbAdapter.ts'], highlight: ['ui', 'state', 'writes', 'store', 'idb'] },
            { text: 'Project preparation performs source-shape validation first (including full AppState validation for schema v10/v11), then schema migration through loadProjectState and migrateState, final validation and normalization, and only then persistence. Legacy localStorage document keys are retained only as read-only migration and recovery input. Epoch 1 has no cleanup, fallback, or dual-write path; old-tab or rollback drift blocks editing and preserves both sources instead of choosing a winner.',
              files: ['services/loadProjectState.ts', 'services/migration.ts', 'services/localWorkspace/legacy.ts', 'services/localWorkspace/LocalWorkspaceStore.ts'], highlight: ['mig', 'legacy', 'idb'] },
            { text: 'The canvas is not a <canvas> — it is absolutely-positioned DOM. That choice is why thumbnails need the PDF pipeline (you cannot screenshot a DOM canvas), and why editor chrome uses an isolation:isolate wrapper so user z-indexes can never paint over selection boxes. PDF export remains entirely client-side through jsPDF and shares text layout decisions with the canvas.',
              files: ['components/Canvas.tsx', 'components/canvas/CanvasElement.tsx', 'components/canvas/ReadOnlyPagePreview.tsx', 'services/pdfService.ts', 'services/textLayout.ts'], highlight: ['state', 'canvas', 'pdf'] },
            { text: 'The Hierarchy Generator describes a whole product as two JavaScript programs. Since schema v9 they persist inside AppState — and because opening someone else’s project must never execute their code, preview runs in a sandboxed iframe + disposable worker, never in the app realm.',
              files: ['components/HierarchyGeneratorModal.tsx', 'services/generatorSandbox.ts'], highlight: ['state', 'gen'] },
        ],
    },
    {
        id: 'cloud-save',
        title: 'Save to cloud: commits and the If-Match dance',
        blurb: 'Every save is an immutable full snapshot; heads advance by compare-and-swap.',
        diagram: [
            '{{menu:CloudMenu}} ─▶ {{api:cloudApi.ts}} ─▶ {{route:POST /api/projects/:id/commits}}',
            '                                              │ If-Match: <head tag>',
            '                                              ▼',
            '{{val:validateAppState}} ─▶ {{codec:stateCodec gzip}} ─▶ {{cas:CAS head advance}}',
            '                                              │ stale? ──▶ {{409:409 conflict}}',
        ],
        steps: [
            { text: 'The Cloud menu is a three-way branch: signed out, signed in without a username, signed in with one. The username gate exists because every commit carries a public handle — and it is deliberately absent from routes that only reduce exposure (unpublish, delete), so legacy accounts can always clean up.',
              files: ['components/cloud/CloudMenu.tsx'], highlight: ['menu'] },
            { text: 'Every server call the cloud features make goes through one typed wrapper: services/cloudApi.ts. When you add an endpoint, it gets a function here — no fetch calls scattered through components.',
              files: ['services/cloudApi.ts'], highlight: ['api'] },
            { text: 'A commit is a full snapshot, not a diff — that decision (made before any code) is why version history, restore, fork, and merge are all simple reads of one row.',
              files: ['server/routes/projects.js'], highlight: ['route'] },
            { text: 'Before anything is stored, the browser-safe implementation in shared/validateAppState.js checks shape, a 5 MB size cap, and node/element count caps; server/validateAppState.js remains its compatibility re-export. The server has exactly three call sites — project create, commits, and the merged result at the end of a merge. Publish is not one of them: it takes listing fields and an If-Match head, never a state.',
              files: ['shared/validateAppState.js', 'server/validateAppState.js', 'server/routes/projects.js', 'server/routes/mergeRequests.js'], highlight: ['val'] },
            { text: 'Snapshots are gzip’d by stateCodec on write and inflated on read. insertCommit (server/routes/projects.js) stamps an app-generated millisecond created_at because SQLite’s CURRENT_TIMESTAMP has whole-second resolution: without it, two saves in one second would tie and “newest first” would fall through to a random UUID id. This one never shipped broken — the commit that first built the history API already carried the stamp and the ORDER BY it protects.',
              files: ['server/stateCodec.js', 'server/routes/projects.js'], highlight: ['codec'] },
            { text: 'Saves carry a strong If-Match head tag; the server advances the head by transactional compare-and-swap. A stale save gets a stable 409 and leaves no orphan commit. CORS had to explicitly admit the If-Match header for any of this to work cross-origin.',
              files: ['server/routes/projects.js', 'server/projectLocks.js', 'server/app.js'], highlight: ['cas', '409'] },
        ],
    },
    {
        id: 'publish',
        title: 'Publish: the pinned snapshot',
        blurb: 'Public means the version you published — never your live working head.',
        diagram: [
            '{{wizard:PublishModal}} ─▶ {{thumbs:thumbnails: jsPDF → pdfjs → WebP}}',
            '        │',
            '        ▼',
            '{{pub:POST …/publish}} ─ validate → lock → write ─▶ {{pin:published_commit_id}}',
            '        │                                             ▲',
            '{{edit:PATCH …/publication}} ── metadata only, never moves ┘',
            '{{gal:gallery readers}} ──── only ever see the pin',
        ],
        steps: [
            { text: 'The publish wizard collects a description, tags, and up to six preview pages, and renders the previews live before you commit to anything. Preview selection re-renders from the published commit — never from your working state — so the shop window can never advertise a page the download doesn’t contain.',
              files: ['components/cloud/PublishModal.tsx', 'components/cloud/PreviewPagePicker.tsx'], highlight: ['wizard'] },
            { text: 'Thumbnails exist because the DOM canvas can’t be screenshotted: render to an in-memory PDF (jsPDF), rasterize with pdfjs-dist, downscale to WebP. The server re-validates every image by magic bytes and caps them at 300 KB.',
              files: ['services/thumbnailService.ts', 'server/routes/projects.js'], highlight: ['thumbs'] },
            { text: 'Publishing validates, locks, and writes inside one transaction (withTransaction pins a Postgres client and serializes SQLite under BEGIN IMMEDIATE).',
              files: ['server/routes/projects.js', 'server/projectLocks.js', 'server/db.js'], highlight: ['pub'] },
            { text: 'The load-bearing column: published_commit_id. Ordinary saves and merges advance only the private head; public content changes only on explicit republish. This model exists because a whole-branch review caught gallery readers being served the live head — a disclosure hazard once generator source became public.',
              files: ['server/migrations/index.js'], highlight: ['pin'] },
            { text: 'Listing metadata (name, description, tags) is pinned at publish time too — privately renaming a project stopped silently renaming its gallery card. A later round added PATCH /api/projects/:id/publication: edit the listing without republishing, guarded by a composite If-Match token (published_commit_id AND published_at, because republishing an unchanged commit is legal).',
              files: ['server/routes/projects.js', 'shared/publicationTag.js', 'components/cloud/EditListingModal.tsx'], highlight: ['edit'] },
            { text: 'Everything a gallery reader touches — detail, download, open-in-editor, fork — resolves the published commit. “Recently updated” sorts by published_at, which metadata edits deliberately never move: keeping a listing tidy must not be free promotion.',
              files: ['server/routes/gallery.js'], highlight: ['gal'] },
        ],
    },
    {
        id: 'fork-merge',
        title: 'Fork → merge request: the three-way diff at work',
        blurb: 'One plain-JS engine, server-side: it recomputes the diff on every view of the request and enforces it again at merge time. The client renders what comes back.',
        diagram: [
            '{{up:upstream (public)}} ──fork──▶ {{fork:private fork + lineage}}',
            '     │  base = common ancestor         │ edits, saves',
            '     ▼                                 ▼',
            '{{mr:merge request}} ◀──propose── {{head:fork head commit}}',
            '     │ diff recomputed LIVE on every view',
            '     ▼',
            '{{tw:threeWayDiff}} ─ conflicts? ─▶ {{merge:merge under lock}} / {{block:refuse}}',
        ],
        steps: [
            { text: 'Forking a public project — including your own — copies the published commit into a brand-new private project, recording exactly which project and commit it came from. Forks never appear in the gallery.',
              files: ['server/routes/projects.js'], highlight: ['up', 'fork'] },
            { text: 'A merge request proposes the fork’s head back upstream. The review page shows a structured change list — templates and variants, not text lines — plus a rendered before/after preview.',
              files: ['server/routes/mergeRequests.js', 'pages/MergeRequestPage.tsx'], highlight: ['mr', 'head'] },
            { text: 'The diff is recomputed live every time the request is viewed — never a stale snapshot — so a request that becomes conflicted after the fact (upstream changed the same thing) is caught before anyone clicks merge.',
              files: ['server/routes/mergeRequests.js'], highlight: ['mr'] },
            { text: 'threeWayDiff compares the fork’s changes and upstream’s changes against their common ancestor. Six genuine conflict classes, and only these six: same template edited differently, a variant removed on one side and modified on the other, a variant added on both sides with different content, a variant renamed differently on both sides, the node hierarchy changed differently, and the generator — treated as one atomic value, never line-merged. Changes that do not overlap coexist.',
              files: ['shared/diff.js'], highlight: ['tw'] },
            { text: 'Merging re-verifies no conflict immediately before writing, inside the same lock that pins the target head, refuses already-merged/closed requests, and runs the merged result back through the shared validateAppState implementation via its server compatibility re-export. The Merge button’s visibility comes from the server’s own isTargetOwner — the client once guessed “whoever isn’t the author” and broke on self-forks.',
              files: ['server/routes/mergeRequests.js', 'shared/validateAppState.js', 'server/validateAppState.js'], highlight: ['merge', 'block'] },
            { text: 'A schema mismatch between fork and upstream deliberately blocks the diff until the fork re-saves on the current version — that guard is in the merge-request route, not the engine. The engine itself ignored the layers, overflow and padding schema changes entirely, because it diffs whole templates.',
              files: ['server/routes/mergeRequests.js', 'shared/diff.js', 'services/migration.ts'], highlight: ['tw'] },
        ],
    },
    {
        id: 'pdf-export',
        title: 'Export: one text engine, two renderers',
        blurb: 'Canvas and PDF used to each do their own text layout. Neither respected the box.',
        diagram: [
            '{{req:element + box}} ─▶ {{engine:textLayout.ts (pure)}}',
            '                          │ segmentation · wrap · ellipsis · shrink',
            '            ┌─────────────┴─────────────┐',
            '            ▼                           ▼',
            '{{cadapt:canvas adapter}}         {{padapt:jsPDF adapter}}',
            '            ▼                           ▼',
            '{{dom:DOM canvas}}                {{doc:exported PDF}}  + {{svg:svg2pdf normalization}}',
        ],
        steps: [
            { text: 'services/textLayout.ts is renderer-independent: segmentation, greedy wrap, ellipsis, shrink-to-fit, block sizing — with text measurement injected, so the same decisions run everywhere. Four overflow modes (clip, ellipsis, shrink, visible) plus an independent wrap toggle.',
              files: ['services/textLayout.ts', 'services/textOverflow.ts'], highlight: ['engine'] },
            { text: 'Two thin adapters: one over an offscreen canvas context, one over jsPDF width metrics. A parity suite feeds both identical fake metrics and asserts identical lines, truncation, and clip flags.',
              files: ['services/canvasTextLayout.ts', 'services/pdfTextLayout.ts'], highlight: ['cadapt', 'padapt'] },
            { text: 'Quiet correctness lives here: the ellipsis search was a binary search over grapheme counts — which assumes measured width is monotonic in count; it isn’t guaranteed to be, so it became a linear scan. Greedy wrap was O(n²) re-measuring whole candidate lines and was rewritten single-pass, with tests asserting bounded measure-call counts.',
              files: ['services/textLayout.ts', 'services/graphemes.ts'], highlight: ['engine'] },
            { text: 'Text padding: one 87-line module whose single geometry function, resolveTextContentBox, shrinks the box before the engine ever sees it. Canvas, the inline overlay editor, and PDF all consume the same content box.',
              files: ['services/textPadding.ts'], highlight: ['req'] },
            { text: 'SVG export is a tree-transform pipeline before svg2pdf sees anything: hsl()/8-digit-hex normalized to rgb + opacity attributes (svg2pdf silently drops what it can’t parse), element opacity baked into the SVG’s own opacity scopes (svg2pdf replaces outer alpha rather than multiplying), grayscale as a desaturation pass with the full CSS named-color table.',
              files: ['services/svgColorNormalize.ts'], highlight: ['svg'] },
            { text: 'Link annotations became a helper called from every element branch after svg and line elements silently skipped them — the shared doc.link() block sat below a continue. Byte-level tests read the annotations back out of the produced PDF.',
              files: ['services/pdfService.ts'], highlight: ['doc'] },
        ],
    },
    {
        id: 'signup',
        title: 'A signup’s journey',
        blurb: 'better-auth with app-owned choke points: cap, verification, username, admin-path denial.',
        diagram: [
            '{{form:signup form / Google OAuth}} ─▶ {{auth:better-auth /api/auth/*}}',
            '                                        │ databaseHooks.user.create.before',
            '                                        ▼',
            '{{cap:signup cap check}} ─ full? ─▶ {{wait:waitlist panel}}',
            '     │ open',
            '     ▼',
            '{{verify:email verification}} ─▶ {{welcome:/welcome username gate}} ─▶ {{gated:content-creating routes}}',
        ],
        steps: [
            { text: 'better-auth mounts at /api/auth before express.json — its handler consumes its own bodies. Everything app-specific hangs off hooks, not forked library code.',
              files: ['server/auth.js', 'server/app.js'], highlight: ['auth'] },
            { text: 'The signup cap lives in databaseHooks.user.create.before — the single choke point both email signup and first-time Google OAuth pass through; returning OAuth users never create a row, so they never hit it. Path-based middleware was rejected for exactly that OAuth blind spot.',
              files: ['server/auth.js', 'server/signupCap.js'], highlight: ['cap'] },
            { text: 'Only verified accounts count toward the cap, and the counter fails open by design: a broken count query must not lock the front door. The waitlist endpoint treats duplicates as idempotent success so it never reveals membership.',
              files: ['server/signupCap.js'], highlight: ['cap', 'wait'] },
            { text: 'Email delivery is one fail-safe module: Resend’s HTTP API when a key is configured, console logging when not — and a missing key never weakens sign-in blocking. The dotenv seals (present-but-empty, never delete) guard every test/tooling surface from sending real mail.',
              files: ['server/email.js'], highlight: ['verify'] },
            { text: 'Accounts can exist with username = null (OAuth, legacy). /welcome blocks content creation until one is set; requireUsername guards the six routes that create or attach public content (project create, commits, publish, fork, merge-request create, reviews) — and deliberately not unpublish/delete/merge-close, so a legacy account can always clean up its own data.',
              files: ['pages/WelcomePage.tsx', 'server/middleware/guards.js'], highlight: ['welcome', 'gated'] },
            { text: 'hooks.before also denies /admin/* inside better-auth — where it sees the normalized path. Express-level blocking was bypassable with percent-encoded dot-segments that normalized back to /admin/* inside the library; red tests proved unban and role promotion answered 200 to a non-admin before the fix.',
              files: ['server/auth.js'], highlight: ['auth'] },
        ],
    },
];
